import type { BuilderComponentDefinition } from "@/lib/simulator/builder/types";

export const DEFAULT_BUILDER_LIBRARY: BuilderComponentDefinition[] = [
  {
    id: "chassis-starter",
    displayName: "Starter Chassis",
    category: "structure",
    simulatorRole: "chassis",
    description: "Compact training chassis with room for two drive motors and one arm stack.",
    color: "#1d4ed8",
    dimensions: { width: 18, height: 4, depth: 16 },
    attachmentPoints: ["front-left", "front-right", "rear-left", "rear-right", "center-top"],
    assetSource: "builtin",
    tags: ["base", "robot", "frame"],
  },
  {
    id: "drive-motor",
    displayName: "Drive Motor",
    category: "drive",
    simulatorRole: "driveMotor",
    description: "Mapped to drivetrain power and encoder values in the simulator.",
    color: "#0f766e",
    dimensions: { width: 4, height: 4, depth: 6 },
    attachmentPoints: ["shaft"],
    defaultDeviceName: "driveMotor",
    assetSource: "builtin",
    tags: ["motor", "wheel", "encoder"],
  },
  {
    id: "traction-wheel",
    displayName: "Traction Wheel",
    category: "drive",
    simulatorRole: "wheel",
    description: "Wheel module for simple tank-drive lesson robots.",
    color: "#f59e0b",
    dimensions: { width: 4, height: 4, depth: 2 },
    attachmentPoints: ["hub"],
    assetSource: "builtin",
    tags: ["wheel", "drive"],
  },
  {
    id: "arm-motor",
    displayName: "Arm Motor",
    category: "mechanism",
    simulatorRole: "armMotor",
    description: "Motorized pivot for lift or arm lessons.",
    color: "#db2777",
    dimensions: { width: 4, height: 4, depth: 6 },
    attachmentPoints: ["pivot", "mount"],
    defaultDeviceName: "armMotor",
    assetSource: "builtin",
    tags: ["arm", "motor", "mechanism"],
  },
  {
    id: "arm-segment",
    displayName: "Arm Segment",
    category: "mechanism",
    simulatorRole: "armSegment",
    description: "Lightweight arm beam for lift and claw demonstrations.",
    color: "#e5e7eb",
    dimensions: { width: 3, height: 18, depth: 3 },
    attachmentPoints: ["base", "tip"],
    assetSource: "builtin",
    tags: ["beam", "arm"],
  },
  {
    id: "servo-standard",
    displayName: "Standard Servo",
    category: "mechanism",
    simulatorRole: "servo",
    description: "General servo for claws, gates, or small mechanisms.",
    color: "#7c3aed",
    dimensions: { width: 3, height: 3, depth: 5 },
    attachmentPoints: ["horn", "mount"],
    defaultDeviceName: "servo",
    assetSource: "builtin",
    tags: ["servo", "rotation"],
  },
  {
    id: "claw-basic",
    displayName: "Basic Claw",
    category: "mechanism",
    simulatorRole: "claw",
    description: "Simple open-close claw for object pickup lessons.",
    color: "#ef4444",
    dimensions: { width: 5, height: 5, depth: 4 },
    attachmentPoints: ["mount"],
    defaultDeviceName: "clawServo",
    assetSource: "builtin",
    tags: ["claw", "intake"],
  },
  {
    id: "distance-sensor",
    displayName: "Distance Sensor",
    category: "sensor",
    simulatorRole: "sensor",
    description: "Future-facing component for autonomous sensor lessons.",
    color: "#0891b2",
    dimensions: { width: 3, height: 2, depth: 3 },
    attachmentPoints: ["front"],
    defaultDeviceName: "distanceSensor",
    assetSource: "builtin",
    tags: ["sensor", "autonomous"],
  },
];
